"""Agregacja kategorii sprzedawców (mrch_catg_nm) do kategorii głównych.

Mapowanie przepisane 1:1 z zapytania SQL (kolumna kategoria_glowna). Kolejność ma znaczenie: tak jak w CASE,
wygrywa pierwsze dopasowanie (np. 'THE RITZ-CARLTON' trafia do hoteli, choć jest też na liście usług).
Nazwy porównujemy po UPPER(TRIM(...)).
"""

INNE = "Inne"

GLOWNE = {
    "Duże supermarkety": ["GROCERY STORES/SUPERMARKETS"],
    "Małe sklepy spożywcze": ["MISC FOOD STORES - DEFAULT"],
    "Restauracje i miejsca do jedzenia": ["EATING PLACES AND RESTAURANTS"],
    "Stacje benzynowe": ["SERVICE STATIONS"],
    "Fast Foody": ["FAST FOOD RESTAURANTS"],
    "Piekarnie i cukiernie": ["BAKERIES"],

    "Baza noclegowa i hotele": [
        "HOTELS/MOTELS/RESORTS", "SHERATON", "HOTEL IBIS", "RADISSON HOTEL", "NOVOTEL", "HOTEL MERCURE", "MARRIOTT",
        "HILTON", "PARK INNS INTERNATIONAL", "HOLIDAY INN", "DOUBLETREE HOTEL", "SCANDIC HOTELS", "RADISSON BLU",
        "COURTYARD BY MARRIOTT", "HAMPTON INN", "DOLCE HOTELS AND RESORTS", "PREMIER TRAVEL INNS", "SOFITEL HOTELS",
        "HOTELES MELIA", "REGENT INTERNATIONAL HOTELS", "MARATIM", "WESTIN", "NICKELODEON SUITES", "CROWNE PLAZA HOTELS",
        "DISNEY RESORTS", "STEIGENBERGER", "TOWN & COUNTRY RESORT/CONV CTR", "HILTON GARDEN INN", "CAMPANILE",
        "HILTON INTERNATIONAL", "PARK PLAZA HOTEL", "WYNDHAM", "TOWNEPLACE SUITES", "DORINT HOTELS", "MOEVENPICK HOTELS",
        "TRAVELODGE", "SONESTA HOTEL", "RESIDENCE INN", "AMERISUITES", "AUTOGRAPH", "FOUR SEASONS", "FAIRMONT HOTEL",
        "SPRINGHILL SUITES", "MILLENNIUM HOTELS", "DAYS INN", "SUPER 8 MOTEL", "W HOTELS", "CAESAR'S HOTEL AND CASINO",
        "OXFORD SUITES", "HOTEL INDIGO", "FAIRFIELD INN", "HOSPITALITY INNS", "MOTEL 6", "FLAMINGO HOTELS", "PRINCE HOTEL",
        "PARIS LAS VEGAS HOTEL", "LA QUINTA INN AND SUITES", "ECONOLODGE", "EXCALIBUR HOTEL AND CASINO", "WALDORF",
        "RIO HOTELS", "QUALITY INN", "HOMEWOOD SUITES", "VENETIAN RESORT HOTEL CASINO", "EMBASSY SUITES",
        "PULLMAN INTERNATIONAL HOTELS", "PROTEA HOTELS", "BALLY'S HOTEL AND CASINO", "DRURY INN", "COUNTRY INN BY CARLSON",
        "SOUTHERN SUN HOTELS", "IMPERIAL LONDON HOTELS", "CARLTON HOTELS", "FIRST HOSPITALITY HOTELS", "BELLAGIO",
        "AMERICAS BEST VALUE INN", "CHATEAU ELAN WINERY AND RESORT", "CLARION HOTEL", "STRATOSPHERE HOTEL AND CASINO",
        "MANDARIN ORIENTAL HOTEL", "CURIO HOTELS", "RELAX INNS", "CLUBCORP/CLUBRESORTS", "OMNI HOTEL", "RAMADA INN",
        "LOEWS HOTEL", "DELTA HOTEL", "MICROTEL INNS & SUITES", "RED ROOF INN", "SOKOS HOTELS", "CITY LODGE HOTELS",
        "SANDMAN HOTELS", "SOHO GRAND HOTEL", "ROYAL HOTELS", "GREAT WOLF", "CANOPY HOTELS", "ST. REGIS HOTEL",
        "RENAISSANCE HOTELS", "PENINSULA HOTELS", "HOME2 SUITES", "HARRAH'S HOTELS AND CASINOS", "BEST WESTERN",
        "INTER-CONTINENTAL", "GOLDEN TULIP", "HYATT", "THE RITZ-CARLTON", "MOXY", "GAYLORD PALMS", "ALOFT",
        "SHANGRI-LA INTERNATIONAL", "HYATT PLACE", "LA MANSION DEL RIO", "JUMEIRAH ESSEX HOUSE",
        "TRAILER PARKS AND CAMPGROUNDS",
    ],

    "Zakupy spożywcze i gastronomia (pozostałe)": [
        "FREEZER/MEAT LOCKERS", "BARS/TAVERNS/LOUNGES/DISCOS", "CATERERS",
    ],

    "Transport i motoryzacja (pozostałe)": [
        "CAR WASHES", "PARKING LOTS,METERS,GARAGES", "TOLLS AND BRIDGE FEES", "PASSENGER RAILWAYS", "AUTOMATED FUEL DISPENSERS",
        "AUTO SERVICE SHOPS/NON DEALER", "TAXICABS/LIMOUSINES", "BUS LINES", "CAR & TRUCK DEALERS/NEW/USED",
        "MISC REPAIR SERVICES", "RYANAIR", "MOTOR FREIGHT CARRIERS", "REAL EST AGNTS & MGRS RENTALS",
        "AUTOMOBILE RENTAL AGENCY", "MOTORCYCLE DEALERS", "FUEL DEALERS", "AIRLINES, AIR CARRIERS",
        "TIRE RETREAD/REPAIR SHOPS", "AUTO BODY REPAIR SHOPS", "MISC AUTO DEALERS - DEFAULT", "STEAMSHIP/CRUISE LINES",
        "RADIO/TV/STEREO REPAIR SHOP", "HEATING, PLUMBING, AIR COND", "SMALL APPLIANCE REPAIR DEF",
        "ELECTRIC VEHICLE CHARGING", "LOT (POLAND)", "AIR COND/REFRIG REPAIR SHOP", "CAR & TRUCK DEALERS/USED ONLY",
        "MOTOR HOME/RV RENTALS", "TRUCK/UTILITY TRAILER RENTALS", "SIXT CAR RENTAL", "AVIS RENT-A-CAR", "TOWING SERVICES",
        "HERTZ RENT-A-CAR", "BOAT DEALERS", "SAS", "ENTERPRISE RENT-A-CAR", "AUTO ASSOCIATIONS", "KLM",
        "AFFILIATED AUTO RENTAL", "LUFTHANSA", "EASYJET", "EMIRATES AIRLINES", "ALAMO RENT-A-CAR", "AIR ASTANA",
        "BUDGET RENT-A-CAR", "NATIONAL CAR RENTAL", "TURKISH AIRLINES", "DOLLAR RENT-A-CAR", "IBERIA",
        "SN BRUSSELS AIRLINES", "SWISS INTERNATIONAL AIRLINES", "AMERICAN", "QANTAS", "LAN AIR", "WIZZ AIR",
        "BRITISH AIRWAYS", "UNITED", "THRIFTY CAR RENTAL", "AGENCY RENT-A-CAR", "AIR FRANCE", "AVIANCA", "DELTA",
        "AERO ARGENT", "CEBU PACIFIC AIRLINES", "JETSTAR AIRWAYS", "HAWAIIANAIR", "AIR ALGERIE", "QATAR AIRWAYS",
        "NORWEGIAN AIR SHUTTLE", "EGYPTAIR", "PAL AIR", "BRAATHENS RGNL AIRLINES (BRA)", "PAYLESS CAR RENTAL", "COPA",
        "EUROP CAR",
    ],

    "Zdrowie i uroda": [
        "COSMETIC STORES", "DRUG STORES & PHARMACIES", "BEAUTY/BARBER SHOPS", "MED/HEALTH SERVICES - DEF",
        "DENTISTS/ORTHODONTISTS", "VETERINARY SERVICES", "DOCTORS & PHYSICIANS", "HEALTH & BEAUTY SPAS", "OPTICIANS",
        "HOSPITALS", "DRUGS/DRUGGISTS SUNDRIES", "DENTAL/LAB/MED EQUIPMENT", "MASSAGE PARLORS", "MEDICAL/DENTAL LABS",
        "PODIATRISTS/CHIROPODISTS", "TESTING LABS (NON-MEDICAL)", "OSTEOPATHS", "NURSING/PERSONAL CARE FAC",
        "CHIROPRACTORS",
    ],

    "Zakupy detaliczne i dom": [
        "VARIETY STORES", "FAMILY CLOTHING STORES", "CANDY/NUT/CONFECTION STORES", "DISCOUNT STORES",
        "HOME SUPPLY WAREHOUSE STORES", "MENS/WOMENS CLOTHING STORES", "DEPARTMENT STORES", "LUMBER/BUILD. SUPPLY STORES",
        "MISC SPECIALTY RETAIL", "FLORISTS", "BOOK STORES", "PKG STORES/BEER/WINE/LIQUOR", "PET STORES/FOOD & SUPPLY",
        "ELECTRONICS STORES", "FURNITURE/EQUIP STORES", "CIGAR STORES/STANDS", "SHOE STORES", "MISC GENERAL MERCHANDISE",
        "NURSERIES, LAWN/GARDEN SUPPLY", "GIFT, CARD, NOVELTY STORES", "DUTY FREE STORES", "JEWELRY STORES",
        "STATIONERY STORES", "WOMENS READY TO WEAR STORES", "AUTOMOTIVE PARTS STORES", "DAIRY PRODUCT STORES",
        "WOMENS ACCESS/SPECIALTY", "MISC APPAREL/ACCESS STORES", "USED MERCHANDISE STORES", "HOUSEHOLD APPLIANCE STORES",
        "HARDWARE STORES", "MEN/BOYS CLOTHING/ACC STORES", "FABRIC STORES", "LUGGAGE/LEATHER STORES", "PHOTO STUDIOS",
        "PHOTOFINISH LABS/DEV", "FLORIST SUPPLIES/NURSERY STOCK", "BICYCLE SHOPS/SALES/SERVICE",
        "STATIONERY/OFFICE SUPPLIES", "DRAPERY & UPHOLSTERY STORES", "HARDWARE EQUIPMENT/SUPPLIES", "ARTIST/CRAFT SHOPS",
        "GLASS/PAINT/WALLPAPER STORES", "BOOKS/PERIODICALS/NEWSPAPERS", "SHOE REPAIR/SHINE/HAT CLEAN",
        "GLASSWARE/CRYSTAL STORES", "FINANCIAL INST/MERCHANDISE", "RELIGIOUS GOODS STORES", "MOTOR VEHICLE SUPPLY/NEW PARTS",
        "COMPUTER SOFTWARE STORES", "UNIFORMS & COMMERCIAL CLOTHING", "WATCH/CLOCK/JEWELRY REPAIR", "OFFICE/PHOTO EQUIPMENT",
        "CAMERA & PHOTO SUPPLY STORES", "MUSIC STORES/PIANOS", "ELEC RAZOR STORES/SALE/SERV", "POSTAGE STAMPS",
        "FLOOR COVERING STORES", "COMMERCIAL PHOTO/ART/GRAPH", "PAINT, VARNISHES & SUPPLIES", "RECORD STORES",
        "ANTIQUE SHOPS", "PRECIOUS STONES/METALS/JEWELRY", "AUTOMOTIVE TIRE STORES", "ACCOUNTANTS/AUDITORS/BOOKPR",
        "PETROLEUM/PETROLEUM PRODUCTS", "AUTO PAINT SHOPS", "DVD/VIDEO TAPE RENTAL STORES", "STAMP & COIN STORES",
        "NON-FIN INST-STORED VALUE CARD", "MARINAS, SERVICE & SUPPLY", "WIG AND TOUPEE STORES", "COMMERCIAL FURNITURE",
        "CLOTHING/RENT/COSTUME/UNIFO", "DIGITAL GOODS APP(EXCL GAMES)", "ANTIQUE REPRODUCTION STORES",
        "CARPET/UPHOLSTERY CLEANING", "FURNITURE REUPHOLSTERY/REPAIR", "COMBINATION CATALOG & RETAIL",
        "FIREPLACES & ACCESSORIES", "DIGITAL GOODS GAMES", "DIGITAL GOODS BOOKSMOVIEMUSIC", "CATALOG MERCHANT",
        "CHILDREN/INFANTS WEAR STORES", "HOBBY, TOY & GAME STORES",
    ],

    "Rozrywka, kultura i rekreacja": [
        "LOCAL COMMUTER TRANSPORT", "GOVT-OWNED LOTTERIES (NON-US)", "RECREATION SERVICES", "SPORTING GOODS STORES",
        "WHOLESALE CLUBS", "MEMBER CLUBS/SPORT/REC/GOLF", "MOTION PICTURE THEATRES", "AMUSEMENT PARKS/CIRCUS",
        "SPORTING/RECREATIONAL CAMPS", "TOURIST ATTRACTIONS AND XHBT", "TRANSPORTATION SVCS - DEFAULT",
        "BANDS/ORCHESTRAS/ENTERTAIN", "SPORTS/RIDING APPAREL STORES", "COMMERCIAL/PRO SPORTS", "THEATRICAL PRODUCERS",
        "BOWLING ALLEYS", "BETTING/TRACK/CASINO/LOTTO", "VIDEO GAME ARCADES/ESTABLISH", "BILLIARD/POOL ESTABLISHMENT",
        "VIDEO AMUSEMENT GAME SUPPLY", "SWIMMING POOLS/SALES/SERV", "AQUARIUMS/SEAQUARIUMS", "ART DEALERS & GALLERIES",
        "CAMPER TRAILER DEALER", "ARCADE", "GOVERNMENT OWNED LOTTERIES", "TAROM ROMANIAN AIR TRANSPORT",
        "DANCE HALLS/STUDIOS/SCHOOLS",
    ],

    "Usługi, finanse i opłaty urzędowe": [
        "NEWS DEALERS/NEWSSTANDS", "WIRE TRANSFER MONEY ORDER", "UTILITIES/ELEC/GAS/H2O/SANI", "GOV'T SERV - DEFAULT",
        "COURIER SERVICES", "MISC HOME FURNISHING SPECIALTY", "MISC PERSONAL SERV - DEF", "TELECOMMUNICATION EQUIPMENT",
        "QUICK COPY/REPRO SERVICES", "INSURANCE SALES/UNDERWRITE", "BUSINESS SERVICES - DEFAULT", "TAX PAYMENTS",
        "PROFESSIONAL SERVICES - DEF", "COMPUTER PROGRAM/SYS DESIGN", "LAUNDRIES-FAMILY/COMMERCIAL",
        "CHARITABLE/SOC SERVICE ORGS", "MISC PUBLISHING & PRINTING", "ELECTRICAL PARTS/EQUIPMENT", "RELIGIOUS ORGANIZATIONS",
        "DIRECT SELL/DOOR-TO-DOOR", "CONSTRUCTION MATERIALS - DEF", "AGRICULTURAL CO-OPERATIVE", "TRAVEL AGENCIES",
        "LEGAL SERVICES ATTORNEYS", "PLUMBING/HEATING EQUIPMENT", "ORTHOPEDIC GOODS", "COURT COSTS/ALIMONY/SUPPORT",
        "TAILOR/SEAMSTRESS/ALTERS", "PUBLIC WAREHOUSING", "CHEMICALS/ALLIED PRODS - DEF", "SPEC CONTRACTORS - DEFAULT",
        "FINES", "NON-DURABLE GOODS - DEFAULT", "DRY CLEANERS", "LAUNDRY/CLEANING/GARMENT SV",
        "GEN CONTRACTORS RESIDENTL/COML", "COUNSELING SERVICE - ALL", "OPTOMETRISTS/OPHTHALMOLOGISTS",
        "ADVERTISING SERVICES", "NON-FIN INST/FC/MO/TC", "LANDSCAPE/HORTICULTURAL SER", "PAWN SHOPS",
        "INDUSTRIAL SUPPLIES - DEF", "DURABLE GOODS - DEFAULT", "MEMBER ORGANIZATIONS - DEF", "EQUIP/FURN RENT/LEASE SERV",
        "COMPUTERS/PERIPHERALS/SOFTWARE", "SPECIALTY CLEANING/POLISHING", "COMPUTER MAINT/SVCS - DEF", "CARPENTRY",
        "CLEAN/MAINT/JANITORIAL SERV", "COMMERCIAL EQUIPMENT - DEFAULT", "COLLEGES/UNIV/JC/PROFESSION",
        "AIRPORTS/FIELDS/TERMINALS", "METAL SERVICE CENTERS", "MGMT/CONSULT/PUBLIC REL SER", "PIECE GOODS/NOTIONS/DRY GOODS",
        "FUNERAL SERVICE/CREMATORIES", "COMMERCIAL FOOTWEAR", "CABLE, SAT, PAY TV/RADIO SVCS", "ELECTRICAL CONTRACTORS",
        "TELECOMMUNICATION SERVICES", "MASONRY/TILE/PLASTER/INSUL", "RAILROADS", "PUBLIC GOLF COURSES",
        "HEARING AID/SALES/SERVICE", "BOAT RENTALS AND LEASING", "CIVIC/SOCIAL/FRATERNAL ASSC", "FURRIERS AND FUR SHOPS",
        "EMPLOYMENT/TEMP HELP AGEN", "ROOFING/SIDING/SHEET METAL", "ARCHITECTURAL/ENG/SURVEY", "INTRA-GOVERNMENT PURCHASES",
        "OTHER DIRECT MARKETERS", "INVALID MERCHANT CATEGORY", "AMBULANCE SERVICE", "COMPUTER NETWORK/INFO SVCS",
        "INFORMATION RETRIEVAL SERVICES", "TYPESETTING/PLATE MAKING ETC", "WRECKING SALVAGE YARDS",
        "DETECTIVE/PROTECTIVE AGEN", "TAX PREPARATION SERVICE", "BAIL AND BOND PAYMENTS", "TIMESHARES",
        "STENOGRAPHIC SERVICES", "BUYING/SHOPPING SERVICES", "DIRECT MARKETING INSURANCE SVC", "FILMS/VIDEO PRODUCTION/DIST",
        "DATING & ESCORT SERVICES", "ONLINE MARKETPLACES", "SECURITIES BROKERS/DEALERS", "MOTOR HOME DEALERS",
        "DIRECT MKTG-TRAVEL RELATED ARR", "TENT AND AWNING SHOPS", "CONTRACTORS - CONCRETE",
        "CONTINUITY/SUBSCRIPTION MERCHT", "WELDING SERVICES", "POLITICAL ORGANIZATIONS", "MOBILE HOME DEALERS",
        "THE RITZ-CARLTON", "EXTERMINATING/DISINFECT SERV", "MOXY", "SNOWMOBILE DEALERS", "TELEGRAPH SERVICES",
        "LARGE DIGITAL GOODS MERCHANT", "CONSUMER CR REPORTING AGEN", "FLY DUBAI", "MERIDIEN",
        "OUTBOUND TELEMARKETING MERCHNT", "GAYLORD PALMS", "ALOFT", "SHANGRI-LA INTERNATIONAL", "COLLECTION AGENCIES",
        "TYPEWRITER/SALES/SERVICE", "HYATT PLACE", "LA MANSION DEL RIO", "JUMEIRAH ESSEX HOUSE", "SCHOOLS - DEFAULT",
        "TRADE/VOCATIONAL SCHOOLS", "CHILD CARE SERVICES", "ELEMENTARY/SECONDARY SCHOOLS", "BUSINESS/SECRETARIAL SCHOOL",
        "CORRESPONDENCE SCHOOLS",
    ],
}


def _q(s):
    return "'" + s.replace("'", "''") + "'"


def case_sql(col):
    """Wyrażenie SQL CASE zwracające kategorię główną dla kolumny col (już po UPPER(TRIM(...)))."""
    parts = [f"WHEN {col} IN ({', '.join(_q(n) for n in names)}) THEN {_q(label)}" for label, names in GLOWNE.items()]
    return "CASE " + " ".join(parts) + f" ELSE {_q(INNE)} END"
